/**
 * 食堂菜品数据库 (数据来源: 校内小程序)
 *
 * 结构: 校区 → 食堂 → { food, drinks }
 * 加新校区: 在 CANTEEN_DATA 里新增一个校区 key
 * 加新食堂: 在对应校区下新增食堂 key
 * 改菜单: 直接编辑对应数组
 */

const CANTEEN_DATA = {
    "紫金港校区": {
    "大食堂": {
        food: [
            // ===== 风味餐厅 =====
            { name: "毛血旺", area: "风味餐厅", price: "¥7" },
            { name: "杂酱面", area: "风味餐厅", price: "¥16" },
            { name: "蛋挞", area: "风味餐厅", price: "¥3" },
            { name: "黑椒牛腩拌饭", area: "风味餐厅", price: "¥19" },
            { name: "小炒肉", area: "风味餐厅", price: "¥7" },
            { name: "卤鸡腿饭", area: "风味餐厅", price: "¥13" },
            { name: "双椒鸡块刀削面", area: "风味餐厅", price: "¥12" },
            { name: "酸菜肉丝面", area: "风味餐厅", price: "¥12" },
            { name: "潮汕肉卷饭", area: "风味餐厅", price: "¥12" },
            { name: "酸菜鱼", area: "风味餐厅", price: "¥6" },
            { name: "番茄肉酱面", area: "风味餐厅", price: "¥15" },
            { name: "臊子面刀削面", area: "风味餐厅", price: "¥12" },
            { name: "番茄牛肉刀削面", area: "风味餐厅", price: "¥15" },
            { name: "隆江猪脚饭", area: "风味餐厅", price: "¥16" },
            { name: "麻婆豆腐", area: "风味餐厅", price: "¥3.5" },
            { name: "烧鸭饭", area: "风味餐厅", price: "¥15" },
            { name: "五味拌面", area: "风味餐厅", price: "¥3" },
            { name: "鲜香菜鲜肉水饺", area: "风味餐厅", price: "¥10" },
            { name: "香辣鸡腿堡套餐", area: "风味餐厅", price: "¥14" },
            { name: "香菇滑鸡拌饭", area: "风味餐厅", price: "¥14" },
            { name: "煎包", area: "风味餐厅", price: "¥1.2" },
            { name: "炸酱刀削面", area: "风味餐厅", price: "¥16" },
            { name: "酸菜鸡", area: "风味餐厅", price: "¥16" },
            { name: "地三鲜", area: "风味餐厅", price: "¥3" },
            { name: "干锅花菜", area: "风味餐厅", price: "¥3" },
            { name: "招牌豌杂面", area: "风味餐厅", price: "¥15" },
            { name: "汉堡", area: "风味餐厅", price: "¥10" },
            { name: "意面套餐", area: "风味餐厅", price: "¥11" },
            { name: "鸡肉卷", area: "风味餐厅", price: "¥7" },
            { name: "咖喱鸡拌饭", area: "风味餐厅", price: "¥12" },
            { name: "一锅出", area: "风味餐厅", price: "¥13.5" },
            { name: "玫瑰豉油鸡饭", area: "风味餐厅", price: "¥15" },
            { name: "农家一锅香", area: "风味餐厅", price: "¥18" },
            { name: "鸡翅包饭", area: "风味餐厅", price: "¥12" },
            { name: "小鸡炖蘑菇", area: "风味餐厅", price: "¥13" },
            { name: "叉烧饭", area: "风味餐厅", price: "¥19" },
            { name: "葱油拌面", area: "风味餐厅", price: "¥1.5" },
            { name: "酸菜大骨", area: "风味餐厅", price: "¥15" },
            { name: "辣子鸡", area: "风味餐厅", price: "¥6" },
            { name: "锅包肉", area: "风味餐厅", price: "¥5.5" },
            { name: "红烧牛肉面", area: "风味餐厅", price: "¥15" },
            { name: "水煮鱼", area: "风味餐厅", price: "¥18" },
            { name: "土豆炖大鹅", area: "风味餐厅", price: "¥14" },
            { name: "香蕉披萨", area: "风味餐厅", price: "¥7" },
            { name: "荠菜鲜肉水饺", area: "风味餐厅", price: "¥12" },
            { name: "红烧仔排拌饭", area: "风味餐厅", price: "¥16" },
            { name: "酸菜白肉", area: "风味餐厅", price: "¥12" },
            { name: "芝士奶油焗饭", area: "风味餐厅", price: "¥16" },
            { name: "风味拌面", area: "风味餐厅", price: "¥3" },
            { name: "牛肉炒饭", area: "风味餐厅", price: "¥15" },
            { name: "泡椒鸡杂面", area: "风味餐厅", price: "¥13" },
            { name: "剁椒炒饭", area: "风味餐厅", price: "¥8" },
            { name: "酸辣鸡片拌饭", area: "风味餐厅", price: "¥14.5" },
            { name: "外婆菜炒饭", area: "风味餐厅", price: "¥12" },
            { name: "培根披萨", area: "风味餐厅", price: "¥7" },
            { name: "小笼包", area: "风味餐厅", price: "¥12" },
            { name: "雪花鸡柳", area: "风味餐厅", price: "¥6" },
            { name: "牛肉饼套餐", area: "风味餐厅", price: "¥14" },
            { name: "腊肠炒饭", area: "风味餐厅", price: "¥12" },
            { name: "铁锅鸡", area: "风味餐厅", price: "¥15" },
            { name: "酸汤小酥肉", area: "风味餐厅", price: "¥12" },
            { name: "烤肠", area: "风味餐厅", price: "¥5" },
            { name: "煎饺", area: "风味餐厅", price: "¥1" },
            { name: "炒河粉", area: "风味餐厅", price: "¥10" },
            { name: "虾仁炒饭", area: "风味餐厅", price: "¥14" },
            { name: "辣炒鱿鱼须拌饭", area: "风味餐厅", price: "¥22" },
            { name: "笑脸土豆饼", area: "风味餐厅", price: "¥6" },
            { name: "玉米排骨汤", area: "风味餐厅", price: "¥14" },
            { name: "菠萝鸡排饭", area: "风味餐厅", price: "¥14" },
            { name: "烤鸡饭", area: "风味餐厅", price: "¥16" },
            { name: "水煮牛肉", area: "风味餐厅", price: "¥17" },
            { name: "鸡排油泼面", area: "风味餐厅", price: "¥12" },
            { name: "口水鸡", area: "风味餐厅", price: "¥8" },
            { name: "粤式腊肠饭", area: "风味餐厅", price: "¥13" },
            { name: "番茄鸡蛋刀削面", area: "风味餐厅", price: "¥10" },
            { name: "大肉面", area: "风味餐厅", price: "¥16" },
            { name: "肉沫虾仁蒸蛋", area: "风味餐厅", price: "¥6" },
            { name: "鲜肉大馄饨", area: "风味餐厅", price: "¥10" },
            { name: "杀猪菜", area: "风味餐厅", price: "¥16" },
            { name: "小炒牛肉拌饭", area: "风味餐厅", price: "¥19" },
            { name: "黑椒鸡排", area: "风味餐厅", price: "¥8" },
            { name: "胡萝卜鲜肉水饺", area: "风味餐厅", price: "¥9" },
            { name: "翅根", area: "风味餐厅", price: "¥3" },
            { name: "水煮肉片", area: "风味餐厅", price: "¥6" },
            { name: "尖椒鸡", area: "风味餐厅", price: "¥7" },
            { name: "麻婆豆腐拌饭", area: "风味餐厅", price: "¥8" },
            { name: "白桃乌龙茶冻", area: "风味餐厅", price: "¥6" },

            // ===== 休闲餐厅 =====
            { name: "椒麻鸡面", area: "休闲餐厅", price: "¥10" },
            { name: "生煎鸡排", area: "休闲餐厅", price: "¥2.5" },
            { name: "肉酱面", area: "休闲餐厅", price: "¥9" },
            { name: "小酥肉小砂锅", area: "休闲餐厅", price: "¥12" },
            { name: "青椒肉丝面", area: "休闲餐厅", price: "¥12" },
            { name: "鸡丁滑蛋饭", area: "休闲餐厅", price: "¥11" },
            { name: "牛肉小砂锅", area: "休闲餐厅", price: "¥15" },
            { name: "肥牛小砂锅", area: "休闲餐厅", price: "¥15" },
            { name: "黑椒牛肉滑蛋饭", area: "休闲餐厅", price: "¥15.5" },
            { name: "三鲜小砂锅", area: "休闲餐厅", price: "¥13" },
            { name: "腊鸡小砂锅", area: "休闲餐厅", price: "¥12" },
            { name: "香肠小砂锅", area: "休闲餐厅", price: "¥12" },
            { name: "生煎鸡腿", area: "休闲餐厅", price: "¥5.5" },

            // ===== 二楼东区 =====
            { name: "番茄肥牛面", area: "二楼东区", price: "¥16" },
            { name: "凉皮", area: "二楼东区", price: "¥8" },
            { name: "尖椒肉片面", area: "二楼东区", price: "¥10" },
            { name: "椒麻猪肘饭", area: "二楼东区", price: "¥14" },
            { name: "红烧鸡腿", area: "二楼东区", price: "¥4.5" },
            { name: "手撕柠檬鸡", area: "二楼东区", price: "¥6.5" },
            { name: "猪肝面", area: "二楼东区", price: "¥7" },
            { name: "片儿川", area: "二楼东区", price: "¥8" },
            { name: "菌菇肉丝面", area: "二楼东区", price: "¥8" },
            { name: "可乐翅中", area: "二楼东区", price: "¥3.5" },
            { name: "奥尔良鸡胸轻食", area: "二楼东区", price: "¥12" },
            { name: "烘肘饭", area: "二楼东区", price: "¥14" },
            { name: "香干肉丝面", area: "二楼东区", price: "¥12" },
            { name: "酸菜黑鱼面", area: "二楼东区", price: "¥10" },
            { name: "椒麻鸡腿饭", area: "二楼东区", price: "¥15" },

            // ===== 二楼西区 =====
            { name: "三杯鸡套餐", area: "二楼西区", price: "¥9.8" },
            { name: "广式烤鸭套餐", area: "二楼西区", price: "¥11.8" },
            { name: "香烤小鸡腿轻食", area: "二楼西区", price: "¥13" },
            { name: "荷包蛋米线", area: "二楼西区", price: "¥8" },
            { name: "番茄牛肉减脂餐", area: "二楼西区", price: "¥16" },
            { name: "泡椒牛肉米线", area: "二楼西区", price: "¥18" },
            { name: "江西炒米粉", area: "二楼西区", price: "¥12" },
            { name: "黑椒猪柳套餐", area: "二楼西区", price: "¥10.8" },
            { name: "三鲜米线", area: "二楼西区", price: "¥15" },
            { name: "台湾卤肉饭", area: "二楼西区", price: "¥8.8" },
            { name: "香辣牛肉套餐", area: "二楼西区", price: "¥15" },
            { name: "奥尔良鸡胸轻食", area: "二楼西区", price: "¥12" },
            { name: "肥肠米线", area: "二楼西区", price: "¥15" },
            { name: "经典意面套餐", area: "二楼西区", price: "¥8.8" },
            { name: "回锅肉套餐", area: "二楼西区", price: "¥14" },
            { name: "鹿茸菇肉丝米线", area: "二楼西区", price: "¥14" },
            { name: "牛肉炒饭", area: "二楼西区", price: "¥15" },

            // ===== 民族餐厅 =====
            { name: "大盘鸡拌面", area: "民族餐厅", price: "¥10" },
            { name: "过油肉拌面", area: "民族餐厅", price: "¥15" },
            { name: "手抓饭", area: "民族餐厅", price: "¥8" },
            { name: "牛肉粉丝汤", area: "民族餐厅", price: "¥9" },
            { name: "牛肉面", area: "民族餐厅", price: "¥8" },

        ],
        drinks: [
            { name: "豆浆", area: "风味餐厅", price: "¥1" },
            { name: "汽水饮料", area: "风味餐厅", price: "¥1.6" },
            { name: "橙汁", area: "风味餐厅", price: "¥6" },
            { name: "苹果汁", area: "风味餐厅", price: "¥6" },
        ]
    },
    "银泉餐厅": {
        food: [
            // ===== 一楼A区 =====
            { name: "红糖烧饼", area: "一楼A区", price: "¥5" },
            { name: "生日面", area: "一楼A区", price: "¥0" },
            { name: "爆浆芝士球", area: "一楼A区", price: "¥8" },
            { name: "牛肉大葱水饺", area: "一楼A区", price: "¥12" },
            { name: "香菜鲜肉水饺", area: "一楼A区", price: "¥10" },
            { name: "煎饺", area: "一楼A区", price: "¥6" },
            { name: "鸡蛋炒年糕", area: "一楼A区", price: "¥8" },
            { name: "麻辣烫拌", area: "一楼A区", price: "¥0" },
            { name: "肉酱酸辣粉", area: "一楼A区", price: "¥16" },
            { name: "龙骨脆", area: "一楼A区", price: "¥5" },
            { name: "手撕鸡面", area: "一楼A区", price: "¥13.5" },
            { name: "砂锅牛肚", area: "一楼A区", price: "¥22" },
            { name: "烤鸡肉煲仔饭", area: "一楼A区", price: "¥15" },
            { name: "肥牛配炒面", area: "一楼A区", price: "¥20" },
            { name: "番茄滑鱼粉", area: "一楼A区", price: "¥17" },
            { name: "藕盒", area: "一楼A区", price: "¥4" },
            { name: "脆皮香蕉", area: "一楼A区", price: "¥3.5" },
            { name: "梅干菜肉烧饼", area: "一楼A区", price: "¥6" },
            { name: "韭菜虾仁水饺", area: "一楼A区", price: "¥16" },
            { name: "韭菜鸡蛋盒子", area: "一楼A区", price: "¥1.5" },
            { name: "番茄抱蛋粉", area: "一楼A区", price: "¥18" },
            { name: "酸菜滑鱼粉", area: "一楼A区", price: "¥17" },
            { name: "大骨面", area: "一楼A区", price: "¥18" },
            { name: "脆皮五花肉拌饭", area: "一楼A区", price: "¥18" },
            { name: "茴香鲜肉水饺", area: "一楼A区", price: "¥13" },
            { name: "椰香流心球", area: "一楼A区", price: "¥6" },
            { name: "虾仁鲜肉馄饨", area: "一楼A区", price: "¥16" },
            { name: "干煸肥肠煲仔饭", area: "一楼A区", price: "¥20" },
            { name: "椒麻手撕鸡暖锅", area: "一楼A区", price: "¥16" },
            { name: "紫豆桂花米糕", area: "一楼A区", price: "¥3" },
            { name: "小炒肉煲仔饭", area: "一楼A区", price: "¥16" },
            { name: "蛋黄鲜肉馄饨", area: "一楼A区", price: "¥16" },
            { name: "香辣汉堡", area: "一楼A区", price: "¥10" },
            { name: "小酥肉", area: "一楼A区", price: "¥9" },
            { name: "杭椒炒蛋夹馍", area: "一楼A区", price: "¥6" },
            { name: "番茄肥牛面", area: "一楼A区", price: "¥18" },
            { name: "金枪鱼拌饭", area: "一楼A区", price: "¥19" },
            { name: "藤椒鸡排", area: "一楼A区", price: "¥5.5" },
            { name: "肉末杭椒炒面", area: "一楼A区", price: "¥15" },
            { name: "虾饼", area: "一楼A区", price: "¥1.5" },
            { name: "瓦香鸡", area: "一楼A区", price: "¥15.5" },
            { name: "铁板年糕", area: "一楼A区", price: "¥2" },
            { name: "香辣汉堡套餐", area: "一楼A区", price: "¥14" },
            { name: "双拼干拌馄饨", area: "一楼A区", price: "¥16" },
            { name: "酸辣牛肉粉", area: "一楼A区", price: "¥23" },
            { name: "爆浆软麻花", area: "一楼A区", price: "¥5.5" },
            { name: "双拼汤馄饨", area: "一楼A区", price: "¥16" },
            { name: "酸菜肥牛粉", area: "一楼A区", price: "¥18" },
            { name: "肥牛拌饭", area: "一楼A区", price: "¥20" },
            { name: "红烧排骨煲仔饭", area: "一楼A区", price: "¥18" },
            { name: "香烤目鱼蛋", area: "一楼A区", price: "¥3.5" },
            { name: "杂粮煎饼", area: "一楼A区", price: "¥6" },
            { name: "薯条", area: "一楼A区", price: "¥6" },
            { name: "广式香肠煲仔饭", area: "一楼A区", price: "¥15" },
            { name: "铁板鱿鱼", area: "一楼A区", price: "¥8" },
            { name: "番茄肥牛粉", area: "一楼A区", price: "¥18" },
            { name: "金沙牛肉煲仔饭", area: "一楼A区", price: "¥22" },
            { name: "肉酱面", area: "一楼A区", price: "¥10" },
            { name: "海苔肉松拌饭", area: "一楼A区", price: "¥16" },
            { name: "水煮鱼片煲", area: "一楼A区", price: "¥17" },
            { name: "蛋挞", area: "一楼A区", price: "¥3" },
            { name: "白糖桂花糕", area: "一楼A区", price: "¥2.5" },
            { name: "杂粮粥", area: "一楼A区", price: "¥2" },
            { name: "奥尔良烤猪肉拌饭", area: "一楼A区", price: "¥18" },
            { name: "豇豆饼", area: "一楼A区", price: "¥2" },
            { name: "菌菇番茄鸡蛋面", area: "一楼A区", price: "¥10" },
            { name: "瘦肉丸", area: "一楼A区", price: "¥10" },
            { name: "抱蛋", area: "一楼A区", price: "¥5" },
            { name: "薯塔", area: "一楼A区", price: "¥5" },
            { name: "菌菇三鲜水饺", area: "一楼A区", price: "¥6" },
            { name: "麻辣豆花牛肉煲", area: "一楼A区", price: "¥22" },
            { name: "虾仁鲜肉干拌馄饨", area: "一楼A区", price: "¥16" },
            { name: "肉末炒粉干", area: "一楼A区", price: "¥11" },
            { name: "肥牛部队锅", area: "一楼A区", price: "¥20" },
            { name: "香辣牛肉面", area: "一楼A区", price: "¥23" },
            { name: "鸭杂粉丝", area: "一楼A区", price: "¥13" },
            { name: "小笼包", area: "一楼A区", price: "¥5" },
            { name: "烤肉夹馍", area: "一楼A区", price: "¥9" },
            { name: "翅包饭", area: "一楼A区", price: "¥12" },

            // ===== 一楼B区 =====
            { name: "原切牛排", area: "一楼B区", price: "¥88" },
            { name: "西冷牛排", area: "一楼B区", price: "¥68" },
            { name: "奥利奥热奶宝", area: "一楼B区", price: "¥6" },
            { name: "香煎牛排", area: "一楼B区", price: "¥34" },
            { name: "日式咖喱肉酱乌冬面", area: "一楼B区", price: "¥17" },
            { name: "鲍汁手打牛肉饼饭", area: "一楼B区", price: "¥34" },
            { name: "经典意面", area: "一楼B区", price: "¥18" },
            { name: "黑椒手打牛肉饼饭", area: "一楼B区", price: "¥32" },
            { name: "黄油菠萝披萨", area: "一楼B区", price: "¥18" },
            { name: "冬阴功MAMA面", area: "一楼B区", price: "¥25" },
            { name: "冬阴功海鲜汤套餐", area: "一楼B区", price: "¥24" },
            { name: "榴莲披萨", area: "一楼B区", price: "¥32" },
            { name: "辣味牛柳意面", area: "一楼B区", price: "¥24" },
            { name: "罗勒叶辣炒饭", area: "一楼B区", price: "¥22" },
            { name: "日式咖喱肉沫饭", area: "一楼B区", price: "¥16" },
            { name: "T骨猪排", area: "一楼B区", price: "¥22" },
            { name: "玛格丽披萨", area: "一楼B区", price: "¥16" },
            { name: "芝士印式鸡排糯米饭", area: "一楼B区", price: "¥18" },
            { name: "海鲜茄汁意面", area: "一楼B区", price: "¥23" },
            { name: "章鱼小丸子", area: "一楼B区", price: "¥8" },
            { name: "薯条", area: "一楼B区", price: "¥6" },
            { name: "泰式咖喱鸡饭", area: "一楼B区", price: "¥15" },
            { name: "咔嚓脆卷饼", area: "一楼B区", price: "¥12" },
            { name: "酸辣印式鸡排糯米饭", area: "一楼B区", price: "¥18" },
            { name: "黑椒牛柳披萨", area: "一楼B区", price: "¥24" },

            // ===== 二楼速选区 =====
            { name: "红糖撞奶", area: "二楼速选区", price: "¥2" },
            { name: "番茄肥牛乌冬面", area: "二楼速选区", price: "¥18" },
            { name: "河南烩菜", area: "二楼速选区", price: "¥10" },
            { name: "干豆角烧鸡木桶饭", area: "二楼速选区", price: "¥15" },
            { name: "乡情手牵手", area: "二楼速选区", price: "¥22" },
            { name: "排骨汤", area: "二楼速选区", price: "¥7" },
            { name: "没芝麻猪肉小烧饼", area: "二楼速选区", price: "¥2.5" },
            { name: "茄汁鱼片", area: "二楼速选区", price: "¥15" },
            { name: "原味奶酪麻糍", area: "二楼速选区", price: "¥8" },
            { name: "黄焖鸡", area: "二楼速选区", price: "¥12" },
            { name: "虫草花乌鸡汤", area: "二楼速选区", price: "¥7" },
            { name: "海苔饼", area: "二楼速选区", price: "¥4" },
            { name: "烤鸭卷", area: "二楼速选区", price: "¥2" },
            { name: "牛肉凉皮", area: "二楼速选区", price: "¥16" },
            { name: "火腿炒饭", area: "二楼速选区", price: "¥7" },
            { name: "隆江猪脚饭", area: "二楼速选区", price: "¥16" },
            { name: "黑椒牛柳意面", area: "二楼速选区", price: "¥18" },
            { name: "桂花乌叶饭", area: "二楼速选区", price: "¥2.5" },
            { name: "回锅肉木桶饭", area: "二楼速选区", price: "¥14" },
            { name: "南瓜粉蒸小块肉", area: "二楼速选区", price: "¥7" },
            { name: "蒸排骨", area: "二楼速选区", price: "¥6" },
            { name: "黑芝麻牛肉小烧饼", area: "二楼速选区", price: "¥4.5" },
            { name: "湘味拌粉", area: "二楼速选区", price: "¥12" },
            { name: "客家盐焗鸡饭", area: "二楼速选区", price: "¥16" },
            { name: "珍珠肉丸", area: "二楼速选区", price: "¥4.5" },
            { name: "花生碎芋泥小烧饼", area: "二楼速选区", price: "¥2.5" },
            { name: "糖蒸南瓜", area: "二楼速选区", price: "¥2" },
            { name: "白芝麻猪肉小烧饼", area: "二楼速选区", price: "¥2.5" },
            { name: "港式烧鸭饭", area: "二楼速选区", price: "¥15" },
            { name: "港式西多士", area: "二楼速选区", price: "¥5" },
            { name: "凉皮", area: "二楼速选区", price: "¥8" },
            { name: "南昌拌粉", area: "二楼速选区", price: "¥7" },
            { name: "肉末金针菇", area: "二楼速选区", price: "¥5" },
            { name: "皮蛋瘦肉粥", area: "二楼速选区", price: "¥2" },
            { name: "叉烧包", area: "二楼速选区", price: "¥2.5" },
            { name: "天妇罗虾", area: "二楼速选区", price: "¥8" },
            { name: "糯米烧卖", area: "二楼速选区", price: "¥2" },
            { name: "玉米烙", area: "二楼速选区", price: "¥5" },
            { name: "地三鲜木桶饭", area: "二楼速选区", price: "¥10" },
            { name: "肉饼蒸蛋", area: "二楼速选区", price: "¥4.5" },
            { name: "烤鸡饭", area: "二楼速选区", price: "¥16" },
            { name: "蒸三鲜", area: "二楼速选区", price: "¥6" },
            { name: "卤豆干", area: "二楼速选区", price: "¥1" },
            { name: "烧鸭双拼", area: "二楼速选区", price: "¥21" },
            { name: "鸡蛋炒刀削面", area: "二楼速选区", price: "¥8" },
            { name: "可可粉漏奶华", area: "二楼速选区", price: "¥13" },
            { name: "水果奶酪麻糍", area: "二楼速选区", price: "¥13" },
            { name: "虾仁肉末拌粉", area: "二楼速选区", price: "¥14" },
            { name: "水晶包", area: "二楼速选区", price: "¥3" },
            { name: "核桃包", area: "二楼速选区", price: "¥2.5" },
            { name: "排骨煲", area: "二楼速选区", price: "¥16" },
            { name: "葱油鲈鱼", area: "二楼速选区", price: "¥7" },
            { name: "奥尔良烤翅", area: "二楼速选区", price: "¥9" },
            { name: "香肠蒸蛋", area: "二楼速选区", price: "¥2.5" },
            { name: "虫草花蒸鸡", area: "二楼速选区", price: "¥7" },
            { name: "咸肉娃娃菜", area: "二楼速选区", price: "¥3.5" },
            { name: "剁椒巴沙鱼", area: "二楼速选区", price: "¥5" },
            { name: "冰豆花", area: "二楼速选区", price: "¥8" },
            { name: "红豆双皮奶", area: "二楼速选区", price: "¥6" },
            { name: "蒸三菇", area: "二楼速选区", price: "¥5" },
            { name: "黯然销魂饭", area: "二楼速选区", price: "¥19" },
            { name: "奶黄包", area: "二楼速选区", price: "¥2.5" },
            { name: "烤鸡双拼", area: "二楼速选区", price: "¥22" },
            { name: "脆皮奶卷", area: "二楼速选区", price: "¥9" },
            { name: "椰香奶冻西米露", area: "二楼速选区", price: "¥8" },

            // ===== 二楼西北风味 =====
            { name: "鸡肉串", area: "二楼西北风味", price: "¥3.5" },
            { name: "孜然炒面", area: "二楼西北风味", price: "¥10" },
            { name: "牛肉串", area: "二楼西北风味", price: "¥5" },
            { name: "番茄鸡蛋泡馍", area: "二楼西北风味", price: "¥12" },
            { name: "香酥肉夹馍", area: "二楼西北风味", price: "¥8" },
            { name: "臊子干拌面", area: "二楼西北风味", price: "¥16" },
            { name: "烤面筋", area: "二楼西北风味", price: "¥3" },
            { name: "羊肉米线", area: "二楼西北风味", price: "¥20" },
            { name: "鸡肉丸串", area: "二楼西北风味", price: "¥7" },
            { name: "酸汤臊子面", area: "二楼西北风味", price: "¥16" },
            { name: "烤肠", area: "二楼西北风味", price: "¥4.5" },
            { name: "手抓饭", area: "二楼西北风味", price: "¥10" },
            { name: "五花肉", area: "二楼西北风味", price: "¥3" },
            { name: "羊肉串", area: "二楼西北风味", price: "¥5" },
            { name: "番茄鸡蛋干拌面", area: "二楼西北风味", price: "¥12" },
            { name: "烤年糕", area: "二楼西北风味", price: "¥2" },
            { name: "番茄鸡蛋汤面", area: "二楼西北风味", price: "¥12" },
            { name: "牛肉泡馍", area: "二楼西北风味", price: "¥19" },
            { name: "羊肉泡馍", area: "二楼西北风味", price: "¥19" },
            { name: "香酥菜夹馍", area: "二楼西北风味", price: "¥6" },
            { name: "油泼拉条子", area: "二楼西北风味", price: "¥18" },
            { name: "BiangBiang面", area: "二楼西北风味", price: "¥18" },

            // ===== 二楼自选区 =====
            { name: "快餐主食", area: "二楼自选区", price: "¥0" },
            { name: "快餐小炒", area: "二楼自选区", price: "¥0" },
        ],
        drinks: [
            { name: "汽水饮料", area: "一楼A区", price: "¥1.6" },
            { name: "罐装可乐", area: "一楼A区", price: "¥3" },
            { name: "青桔柠檬茶", area: "一楼A区", price: "¥10" },
            { name: "青桔柠檬茶", area: "一楼B区", price: "¥10" },
            { name: "汽水饮料", area: "一楼B区", price: "¥1.6" },
            { name: "泡鲁达", area: "二楼速选区", price: "¥5" },
            { name: "酒酿冰奶", area: "二楼速选区", price: "¥2" },
            { name: "葡萄气泡多", area: "二楼速选区", price: "¥6" },
            { name: "百香芒果", area: "二楼速选区", price: "¥10" },
            { name: "蓝莓柠檬茶", area: "二楼速选区", price: "¥9" },
            { name: "冰峰", area: "二楼西北风味", price: "¥5" },
            { name: "牛奶醪糟", area: "二楼西北风味", price: "¥8" },
            { name: "汽水饮料", area: "二楼西北风味", price: "¥1.6" },
            { name: "汽水饮料", area: "二楼自选区", price: "¥1.6" },
        ]
    },
    "临湖餐厅": {
        food: [
            // ===== 一楼 =====
            { name: "快餐小炒", area: "一楼", price: "¥0" },
            { name: "手撕鸡面", area: "一楼", price: "¥12" },
            { name: "腊味粉丝煲", area: "一楼", price: "¥12" },
            { name: "牛肉年糕", area: "一楼", price: "¥15" },
            { name: "牛肉粉丝煲", area: "一楼", price: "¥15" },
            { name: "三鲜粉丝煲", area: "一楼", price: "¥12" },
            { name: "排骨粉丝煲", area: "一楼", price: "¥15" },
            { name: "肥牛粉丝煲", area: "一楼", price: "¥15" },
            { name: "大排面", area: "一楼", price: "¥10" },
            { name: "鱼片粉丝煲", area: "一楼", price: "¥15" },
            { name: "肉酱面", area: "一楼", price: "¥9" },
            { name: "鹌鹑蛋烧肉面", area: "一楼", price: "¥12" },
            { name: "蛋包饭", area: "一楼", price: "¥8" },

            // ===== 二楼 =====
            { name: "铁板鸡排套餐", area: "二楼", price: "¥15.5" },
            { name: "沙拉猪排套餐", area: "二楼", price: "¥15" },
            { name: "铁板猪排套餐", area: "二楼", price: "¥15.5" },
            { name: "千张筒骨煲", area: "二楼", price: "¥15.5" },
            { name: "碳烤鸡排饭", area: "二楼", price: "¥15" },
            { name: "肉酱意大利面", area: "二楼", price: "¥11.5" },
            { name: "麻辣牛腩手擀面", area: "二楼", price: "¥18" },
            { name: "卤肉饭套餐", area: "二楼", price: "¥15" },
            { name: "日式鸡排饭", area: "二楼", price: "¥15" },
            { name: "红烧排骨手擀面", area: "二楼", price: "¥15" },
            { name: "法式奶油鸡排套餐", area: "二楼", price: "¥13.5" },
            { name: "家常回锅肉", area: "二楼", price: "¥13" },
            { name: "铁板牛排套餐", area: "二楼", price: "¥19.5" },
            { name: "西式黑椒牛柳套餐", area: "二楼", price: "¥15" },
            { name: "西式滑蛋牛肉套餐", area: "二楼", price: "¥15" },
        ],
        drinks: [
            { name: "汽水饮料", area: "一楼", price: "¥1.6" },
            { name: "汽水饮料", area: "二楼", price: "¥1.6" },
        ]
    },
    "澄月餐厅": {
        food: [
            // ===== 一楼 =====
            { name: "招牌肥肠小面", area: "一楼", price: "¥17" },
            { name: "肉沫酸辣粉", area: "一楼", price: "¥15" },
            { name: "卤肉饭套餐", area: "一楼", price: "¥8" },
            { name: "椰汁咖喱虾", area: "一楼", price: "¥18" },
            { name: "卡兹脆鸡排", area: "一楼", price: "¥6" },
            { name: "牛腩酸辣粉", area: "一楼", price: "¥18" },
            { name: "韩式金枪鱼拌饭", area: "一楼", price: "¥20" },
            { name: "日式叉烧拌饭", area: "一楼", price: "¥20" },
            { name: "香草鸡扒菠萝饭", area: "一楼", price: "¥20" },
            { name: "肥肠酸辣粉", area: "一楼", price: "¥17" },
            { name: "甘梅红薯条", area: "一楼", price: "¥8" },
            { name: "番茄滑鱼米线", area: "一楼", price: "¥17" },
            { name: "腊味双拼煲仔饭", area: "一楼", price: "¥15" },
            { name: "铁板鱿鱼", area: "一楼", price: "¥8" },
            { name: "蒸饺", area: "一楼", price: "¥5" },
            { name: "金汤肥牛米线", area: "一楼", price: "¥18" },
            { name: "蔬菜沙拉", area: "一楼", price: "¥9" },
            { name: "煎荷包蛋", area: "一楼", price: "¥1" },
            { name: "馄饨双拼", area: "一楼", price: "¥13" },
            { name: "桂花方糕", area: "一楼", price: "¥6" },
            { name: "打抛饭配鸡扒", area: "一楼", price: "¥20" },
            { name: "虾仁鲜肉馄饨", area: "一楼", price: "¥14" },
            { name: "章鱼丸子", area: "一楼", price: "¥8" },
            { name: "农家炒肉煲仔饭", area: "一楼", price: "¥14" },
            { name: "肉酱拌小面", area: "一楼", price: "¥15" },
            { name: "香辣牛腩小面", area: "一楼", price: "¥18" },
            { name: "香煎黑椒牛排套餐", area: "一楼", price: "¥34" },
            { name: "素面", area: "一楼", price: "¥9" },
            { name: "鸡蛋肉松肠粉", area: "一楼", price: "¥10" },
            { name: "火腿鸡蛋肠粉", area: "一楼", price: "¥8" },
            { name: "香菜鲜肉水饺", area: "一楼", price: "¥9.6" },
            { name: "香煎原味牛排", area: "一楼", price: "¥68" },
            { name: "墨西哥牛肉披萨", area: "一楼", price: "¥9" },
            { name: "小锅米线", area: "一楼", price: "¥14" },
            { name: "荠菜鲜肉馄饨", area: "一楼", price: "¥12" },
            { name: "豉油鸡翅煲仔饭", area: "一楼", price: "¥15" },
            { name: "薯条", area: "一楼", price: "¥6" },
            { name: "金汤滑鱼米线", area: "一楼", price: "¥18" },
            { name: "脆皮鲜奶卷", area: "一楼", price: "¥9" },
            { name: "红焖牛腩煲仔饭", area: "一楼", price: "¥24" },
            { name: "莲子黑米糕", area: "一楼", price: "¥5" },
            { name: "可乐饼", area: "一楼", price: "¥4" },
            { name: "蒜蓉虾减脂套餐", area: "一楼", price: "¥19" },
            { name: "土耳其烤肉煲仔饭", area: "一楼", price: "¥14" },
            { name: "韩式烤五花肉", area: "一楼", price: "¥10" },
            { name: "香辣牛肉套餐", area: "一楼", price: "¥20" },
            { name: "金麦流沙包", area: "一楼", price: "¥6" },
            { name: "腊肠肠粉", area: "一楼", price: "¥11" },
            { name: "麻辣香锅", area: "一楼", price: "¥0" },
            { name: "叉烧包", area: "一楼", price: "¥5" },
            { name: "鲜肉小笼汤包", area: "一楼", price: "¥6" },
            { name: "藤椒鸡煲仔饭", area: "一楼", price: "¥16" },
            { name: "肉骨茶", area: "一楼", price: "¥22" },
            { name: "炒金边粉", area: "一楼", price: "¥11" },
            { name: "鸭血粉丝", area: "一楼", price: "¥15" },
            { name: "莓果酸奶舒芙蕾", area: "一楼", price: "¥6" },
            { name: "椰浆饭", area: "一楼", price: "¥8" },
            { name: "韩式炸酱面", area: "一楼", price: "¥18" },
            { name: "回锅肉套餐", area: "一楼", price: "¥14" },
            { name: "奥尔良烤鸡", area: "一楼", price: "¥11" },
            { name: "红烧排骨煲仔饭", area: "一楼", price: "¥18" },
            { name: "潮汕牛腩肠粉", area: "一楼", price: "¥12" },
            { name: "韩式肥牛拌饭", area: "一楼", price: "¥20" },
            { name: "番茄米线", area: "一楼", price: "¥9" },
            { name: "打抛饭", area: "一楼", price: "¥15" },
            { name: "夏威夷风情披萨", area: "一楼", price: "¥9" },
            { name: "五花肉拌饭", area: "一楼", price: "¥18" },
            { name: "T骨猪扒佐意面", area: "一楼", price: "¥22" },
            { name: "肉末鸡蛋肠粉", area: "一楼", price: "¥8" },
            { name: "青瓜虾仁减脂餐", area: "一楼", price: "¥18" },
            { name: "番茄肥牛米线", area: "一楼", price: "¥18" },
            { name: "香甜玉米烙", area: "一楼", price: "¥7" },
            { name: "菌菇牛肉煲仔饭", area: "一楼", price: "¥21" },
            { name: "椰子咖喱鸡", area: "一楼", price: "¥16" },
            { name: "小米枸杞粥", area: "一楼", price: "¥2" },

            // ===== 二楼 =====
            { name: "快餐小炒", area: "二楼", price: "¥0" },
        ],
        drinks: [
            { name: "泰红（泰式红茶）", area: "一楼", price: "¥10" },
            { name: "汽水饮料", area: "一楼", price: "¥1.6" },
        ]
    },
    "玉湖餐厅": {
        food: [
            // ===== 一楼智慧档口 =====
            { name: "鱼香肉丝面", area: "一楼智慧档口", price: "¥12" },
            { name: "素什锦砂锅", area: "一楼智慧档口", price: "¥10" },
            { name: "黄焖排骨砂锅", area: "一楼智慧档口", price: "¥15" },
            { name: "三杯鸡面", area: "一楼智慧档口", price: "¥12" },
            { name: "红烧肉面", area: "一楼智慧档口", price: "¥16" },
            { name: "麻辣虾滑砂锅", area: "一楼智慧档口", price: "¥18" },
            { name: "猪肚鸡砂锅", area: "一楼智慧档口", price: "¥18" },
            { name: "香辣牛蛙面", area: "一楼智慧档口", price: "¥16" },

            // ===== 一楼自选档口 =====
            { name: "金枪鱼蟹柳波奇饭", area: "一楼自选档口", price: "¥18" },
            { name: "番茄肉酱意面", area: "一楼自选档口", price: "¥18" },
            { name: "照烧鸡波奇饭", area: "一楼自选档口", price: "¥15" },
            { name: "香煎巴沙鱼波奇饭", area: "一楼自选档口", price: "¥18" },
            { name: "西班牙红烩牛腩饭", area: "一楼自选档口", price: "¥22" },
            { name: "蘑菇培根意面", area: "一楼自选档口", price: "¥20" },
            { name: "土耳其烤肉饭", area: "一楼自选档口", price: "¥16" },
            { name: "咖喱猪排饭", area: "一楼自选档口", price: "¥17" },
            { name: "东南亚风味自助", area: "一楼自选档口", price: "¥0" },
            { name: "鸡肉蘑菇意面", area: "一楼自选档口", price: "¥18" },
            { name: "脆皮豆腐鸡腿波奇饭", area: "一楼自选档口", price: "¥17" },

            // ===== 二楼风味区 =====
            { name: "刀削番茄鸡蛋面", area: "二楼风味区", price: "¥10" },
            { name: "铁板尖椒牛肉饭", area: "二楼风味区", price: "¥22" },
            { name: "鲜肉水饺", area: "二楼风味区", price: "¥12" },
            { name: "山西臊子面", area: "二楼风味区", price: "¥13" },
            { name: "香菜鲜肉水饺", area: "二楼风味区", price: "¥12" },
            { name: "生日面", area: "二楼风味区", price: "¥0" },
            { name: "马兰头鲜肉水饺", area: "二楼风味区", price: "¥10" },
            { name: "广式烧鸡", area: "二楼风味区", price: "¥35" },
            { name: "飘香拌面", area: "二楼风味区", price: "¥13" },
            { name: "广式烧鸡饭", area: "二楼风味区", price: "¥16" },
            { name: "广式叉烧米粉", area: "二楼风味区", price: "¥22" },
            { name: "广式牛肉米粉", area: "二楼风味区", price: "¥18" },
            { name: "民族小炒", area: "二楼风味区", price: "¥0" },
            { name: "隆江猪脚饭", area: "二楼风味区", price: "¥16" },
            { name: "广式烧鸭", area: "二楼风味区", price: "¥45" },
            { name: "广式双拼饭", area: "二楼风味区", price: "¥21" },
            { name: "酸菜鲜肉水饺", area: "二楼风味区", price: "¥10" },
            { name: "广式烤鸭米粉", area: "二楼风味区", price: "¥17" },
            { name: "广式叉烧饭", area: "二楼风味区", price: "¥19" },
            { name: "香菇鲜肉水饺", area: "二楼风味区", price: "¥10" },
            { name: "芹菜鲜肉水饺", area: "二楼风味区", price: "¥10" },
            { name: "豉香排骨饭", area: "二楼风味区", price: "¥22" },
            { name: "猪耳朵饭", area: "二楼风味区", price: "¥22" },
            { name: "韭菜鲜肉水饺", area: "二楼风味区", price: "¥10" },
            { name: "鸭血粉丝汤", area: "二楼风味区", price: "¥12.5" },
            { name: "黑鱼片汤粉", area: "二楼风味区", price: "¥18" },
            { name: "虾仁鲜肉水饺", area: "二楼风味区", price: "¥18" },
            { name: "牛肉拉面", area: "二楼风味区", price: "¥8" },
            { name: "雪菜排骨面", area: "二楼风味区", price: "¥18" },
            { name: "牛肉粉丝汤", area: "二楼风味区", price: "¥22" },
            { name: "油泼排骨面", area: "二楼风味区", price: "¥18" },
            { name: "麻辣香锅", area: "二楼风味区", price: "¥0" },
            { name: "广式盐焗鸡饭", area: "二楼风味区", price: "¥16" },
            { name: "玉米鲜肉水饺", area: "二楼风味区", price: "¥10" },
            { name: "排骨拌面", area: "二楼风味区", price: "¥18" },
            { name: "油泼牛肉面", area: "二楼风味区", price: "¥22" },
            { name: "荠菜鲜肉水饺", area: "二楼风味区", price: "¥12" },
            { name: "广式烧鸭饭", area: "二楼风味区", price: "¥15" },
            { name: "秘制牛肉面", area: "二楼风味区", price: "¥22" },
            { name: "牛肉拌面", area: "二楼风味区", price: "¥22" },
            { name: "广式猪杂米粉", area: "二楼风味区", price: "¥22" },
            { name: "广式猪肚汤粉", area: "二楼风味区", price: "¥22" },

            // ===== 二楼自选区 =====
            { name: "快餐小炒", area: "二楼自选区", price: "¥0" },
        ],
        drinks: [
            { name: "酸梅汤", area: "二楼风味区", price: "¥2" },
            { name: "汽水饮料", area: "一楼自选档口", price: "¥1.6" },
        ]
    },
    "交叉中心餐厅": {
        food: [
            { name: "爆炒牛肉拌川", area: "交叉中心餐厅", price: "¥22" },
            { name: "虾皇饺", area: "交叉中心餐厅", price: "¥12" },
            { name: "河虾牛肉面", area: "交叉中心餐厅", price: "¥24" },
            { name: "西葫芦饼", area: "交叉中心餐厅", price: "¥2" },
            { name: "芹菜鲜肉小馄饨", area: "交叉中心餐厅", price: "¥6" },
            { name: "杂粮蒸拼", area: "交叉中心餐厅", price: "¥5.5" },
            { name: "虾仁鲜肉大馄饨", area: "交叉中心餐厅", price: "¥14" },
            { name: "河虾面", area: "交叉中心餐厅", price: "¥19" },
            { name: "猪肝肉丝面", area: "交叉中心餐厅", price: "¥15" },
            { name: "生煎灌汤包", area: "交叉中心餐厅", price: "¥2" },
            { name: "老婆饼", area: "交叉中心餐厅", price: "¥2.5" },
            { name: "拌粉", area: "交叉中心餐厅", price: "¥7" },
            { name: "黄鳝仔排面", area: "交叉中心餐厅", price: "¥27" },
            { name: "小米粥", area: "交叉中心餐厅", price: "¥2" },
            { name: "河虾仔排面", area: "交叉中心餐厅", price: "¥23" },
            { name: "快餐小炒", area: "交叉中心餐厅", price: "¥0" },
            { name: "香干肉丝拌川", area: "交叉中心餐厅", price: "¥15" },
            { name: "低卡蔬菜包", area: "交叉中心餐厅", price: "¥5" },
            { name: "黄鳝牛肉面", area: "交叉中心餐厅", price: "¥27" },
            { name: "河虾三鲜面", area: "交叉中心餐厅", price: "¥24" },
            { name: "荷包蛋", area: "交叉中心餐厅", price: "¥1" },
            { name: "新鲜牛肉面", area: "交叉中心餐厅", price: "¥21" },
            { name: "青椒肉丝拌川", area: "交叉中心餐厅", price: "¥15" },
            { name: "河虾鸡块面", area: "交叉中心餐厅", price: "¥21" },
            { name: "河虾大肠面", area: "交叉中心餐厅", price: "¥23" },
            { name: "河虾猪肝面", area: "交叉中心餐厅", price: "¥19" },
            { name: "鸡蛋拌粉", area: "交叉中心餐厅", price: "¥10" },
            { name: "河虾鳝鱼面", area: "交叉中心餐厅", price: "¥27" },
            { name: "玫瑰鲜花饼", area: "交叉中心餐厅", price: "¥3" },
            { name: "黄鳝大肠面", area: "交叉中心餐厅", price: "¥27" },
            { name: "笋尖鲜肉烧卖", area: "交叉中心餐厅", price: "¥8" },
            { name: "蒸饺", area: "交叉中心餐厅", price: "¥6" },
            { name: "蜜汁叉烧包", area: "交叉中心餐厅", price: "¥5" },
            { name: "葱花鸡蛋饼", area: "交叉中心餐厅", price: "¥2.5" },
            { name: "玉米枣发糕", area: "交叉中心餐厅", price: "¥6" },
            { name: "鸡蛋炒手擀面", area: "交叉中心餐厅", price: "¥10" },
            { name: "千刀肉拌粉", area: "交叉中心餐厅", price: "¥12" },
            { name: "番茄鸡蛋拌川", area: "交叉中心餐厅", price: "¥15" },
            { name: "香炸仔排面", area: "交叉中心餐厅", price: "¥19" },
        ],
        drinks: [
            { name: "汽水饮料", area: "交叉中心餐厅", price: "¥1.6" },
        ]
    },
    "东二麦斯威餐吧": {
        food: [
            // ===== 一楼 =====
            { name: "蟹黄排骨套餐", area: "一楼", price: "¥15" },
            { name: "手撕鸡拌面", area: "一楼", price: "¥13.5" },
            { name: "南乳排骨汤面", area: "一楼", price: "¥15" },
            { name: "泰式鸡酱大虾套餐", area: "一楼", price: "¥17" },
            { name: "麻酱凉皮", area: "一楼", price: "¥8" },
            { name: "干锅茶树菇套餐", area: "一楼", price: "¥15" },
            { name: "快餐小炒", area: "一楼", price: "¥0" },
            { name: "鸭血粉丝", area: "一楼", price: "¥12.5" },
            { name: "滑蛋牛肉套餐", area: "一楼", price: "¥15" },
            { name: "脆椒猪肚拌面", area: "一楼", price: "¥18" },
            { name: "黑椒鸡柳套餐", area: "一楼", price: "¥10.8" },
            { name: "肉酱拌面", area: "一楼", price: "¥10" },
            { name: "雪菜肉丝汤面", area: "一楼", price: "¥13.5" },
            { name: "湘味仔鸡套餐", area: "一楼", price: "¥11.8" },
            { name: "香辣牛腩汤面", area: "一楼", price: "¥20" },

            // ===== 二楼 =====
            { name: "奥尔良翅中", area: "二楼", price: "¥9" },
            { name: "黑椒牛排套餐", area: "二楼", price: "¥34" },
            { name: "咖喱鱼丸套餐", area: "二楼", price: "¥12" },
            { name: "红豆米苔", area: "二楼", price: "¥10" },
            { name: "茄汁肉酱焗饭", area: "二楼", price: "¥13" },
            { name: "苹果", area: "二楼", price: "¥3" },
            { name: "猪排意面套餐", area: "二楼", price: "¥18" },
            { name: "香蕉", area: "二楼", price: "¥2" },
            { name: "培根鸡肉卷套餐", area: "二楼", price: "¥20" },
            { name: "双皮奶", area: "二楼", price: "¥6" },
            { name: "金枪鱼披萨", area: "二楼", price: "¥8" },
            { name: "现烤蛋挞", area: "二楼", price: "¥3" },
            { name: "豉汁排骨套餐", area: "二楼", price: "¥18" },
            { name: "韩式冷面", area: "二楼", price: "¥12" },
            { name: "脆炸鳕鱼汉堡", area: "二楼", price: "¥12" },
            { name: "薯条", area: "二楼", price: "¥6" },
            { name: "小番茄", area: "二楼", price: "¥3" },
            { name: "番茄肉酱热狗", area: "二楼", price: "¥13" },
            { name: "咖喱牛肉套餐", area: "二楼", price: "¥26" },
            { name: "黑椒牛肉焗饭", area: "二楼", price: "¥18" },
            { name: "原味鸡块", area: "二楼", price: "¥5" },
            { name: "美味鸡柳", area: "二楼", price: "¥8" },
            { name: "香辣鸡腿堡", area: "二楼", price: "¥13" },
            { name: "韩式牛肉意面", area: "二楼", price: "¥18" },
            { name: "榴莲披萨", area: "二楼", price: "¥8" },
        ],
        drinks: [
            { name: "汽水饮料", area: "一楼", price: "¥1.6" },
            { name: "香柠蜜柚", area: "二楼", price: "¥7" },
            { name: "布丁牛奶", area: "二楼", price: "¥8" },
            { name: "青稞牛奶", area: "二楼", price: "¥9" },
        ]
    },
    "麦香餐厅": {
        food: [
            { name: "香辣牛杂面", area: "麦香餐厅", price: "¥16" },
            { name: "香菇炸酱面", area: "麦香餐厅", price: "¥13" },
            { name: "牛腩土豆粉", area: "麦香餐厅", price: "¥16" },
            { name: "招牌牛腩面", area: "麦香餐厅", price: "¥16" },
            { name: "快餐小炒", area: "麦香餐厅", price: "¥0" },
            { name: "陕西油泼面", area: "麦香餐厅", price: "¥8" },
            { name: "铁板排骨咖喱饭", area: "麦香餐厅", price: "¥16" },
            { name: "牛肚干拌面", area: "麦香餐厅", price: "¥18" },
            { name: "手撕鸡拌面", area: "麦香餐厅", price: "¥13.5" },
        ],
        drinks: [
            { name: "汽水饮料", area: "麦香餐厅", price: "¥1.6" },
        ]
    },
    // TODO: 外卖数据待补充
    "外卖": {
        food: [],
        drinks: []
    }
    },
    "玉泉校区": {},
    "西溪校区": {},
    "华家池校区": {},
    "之江校区": {},
    "舟山校区": {},
    "海宁国际校区": {}
};
